apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-server
spec:
  strategy:
    type: RollingUpdate
  replicas: 3
  minReadySeconds: 15
  template:
    metadata:
      name: simple-server
      labels:
        app: simple-server
    spec:
      containers:
      - image: leon11sj/simple-server:v3
        name: nodejs
        imagePullPolicy: Always
        readinessProbe:
          periodSeconds: 1
          httpGet:
            path: /
            port: 8080
  selector:
    matchLabels:
      app: simple-server
      
      
