apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-server
spec:
  replicas: 3
  template:
    metadata:
      name: simple-server
      labels:
        app: simple-server
    spec:
      containers:
      - image: leon11sj/simple-server:v2
        name: nodejs
  selector:
    matchLabels:
      app: simple-server