apiVersion: v1
kind: Pod
metadata:
  name: simple-server-manual-v2
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
   - image: leon11sj/simple_server
     name: simple-server
     ports:
     - containerPort: 8080
       protocol: TCP
